# Generated by Django 3.0.6 on 2020-09-16 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('duration', models.DurationField()),
                ('eventClass', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('CONFIDENTIAL', 'CONFIDENTIAL')], max_length=16)),
                ('price', models.FloatField(default=0.0)),
                ('relationRequired', models.IntegerField(choices=[(0, 'Public'), (1, 'Introduction'), (2, 'Relationship'), (3, 'Priority Relationship')], default=3)),
                ('categories', models.ManyToManyField(to='MMcalendar.EventCategory')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('summary', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('duration', models.DurationField()),
                ('eventClass', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('CONFIDENTIAL', 'CONFIDENTIAL')], max_length=16)),
                ('price', models.FloatField(default=0.0)),
                ('relationRequired', models.IntegerField(choices=[(0, 'Public'), (1, 'Introduction'), (2, 'Relationship'), (3, 'Priority Relationship')], default=3)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField(default=0)),
                ('dtstart', models.DateTimeField()),
                ('location', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('TENTATIVE', 'TENTATIVE'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], max_length=16)),
                ('transp', models.CharField(default='OPAQUE', max_length=16)),
                ('attendee', models.ManyToManyField(related_name='Attendees', to='MMcalendar.Calendar')),
                ('categories', models.ManyToManyField(to='MMcalendar.EventCategory')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organizer', to='MMcalendar.Calendar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('begin', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('unavailable', models.BooleanField()),
                ('relationship', models.IntegerField(choices=[(0, 'Public'), (1, 'Introduction'), (2, 'Relationship'), (3, 'Priority Relationship')], default=3)),
                ('scope', models.CharField(choices=[('EVD', 'Everyday'), ('WDY', 'Weekdays'), ('WND', 'Weekends'), ('MON', 'Mondays'), ('TUE', 'Tuesdays'), ('WED', 'Wednesdays'), ('THU', 'Thursdays'), ('FRI', 'Fridays'), ('SAT', 'Saturdays'), ('SUN', 'Sundays')], max_length=3)),
                ('active', models.BooleanField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMcalendar.Calendar')),
            ],
        ),
    ]
