# Generated by Django 3.0.6 on 2020-09-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMcalendar', '0003_auto_20200915_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='mainCalendar',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventClass',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('CONFIDENTIAL', 'CONFIDENTIAL')], default='PRIVATE', max_length=16),
        ),
        migrations.AlterField(
            model_name='service',
            name='eventClass',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE'), ('CONFIDENTIAL', 'CONFIDENTIAL')], default='PRIVATE', max_length=16),
        ),
    ]
