# Generated by Django 3.0.6 on 2020-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMcalendar', '0004_auto_20200916_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dtend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='scope',
            field=models.CharField(choices=[('EVD', 'Everyday'), ('WDY', 'Weekdays'), ('WND', 'Weekends'), ('MON', 'Mondays'), ('TUE', 'Tuesdays'), ('WED', 'Wednesdays'), ('THU', 'Thursdays'), ('FRI', 'Fridays'), ('SAT', 'Saturdays'), ('SUN', 'Sundays')], default='EVD', max_length=3),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='unavailable',
            field=models.BooleanField(default=True),
        ),
    ]
