# Generated by Django 3.0.6 on 2020-09-19 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MMcalendar', '0005_auto_20200917_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrule',
            name='relationship',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Introduction'), (2, 'Relationship'), (3, 'Priority Relationship')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='Attendees', to='MMcalendar.Calendar'),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('name', 'owner')},
        ),
    ]
