# Generated by Django 3.0.6 on 2020-09-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMcalendar', '0006_auto_20200918_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrule',
            name='begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabilityrule',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
