# Generated by Django 3.0.6 on 2020-09-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMcalendar', '0008_auto_20200921_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='relationRequired',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('TENTATIVE', 'TENTATIVE'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='TENTATIVE', max_length=16),
        ),
    ]
