# Generated by Django 3.0.6 on 2020-09-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMcalendar', '0009_auto_20200921_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(status='CONFIRMED'), fields=('dtstart',), name='unique_confirmed_event'),
        ),
    ]
