# Generated by Django 3.0.6 on 2020-09-16 01:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('interval', models.DurationField(default=datetime.timedelta(days=1))),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat', models.TextField(max_length=280)),
                ('active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMsocial.Campaign')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMsocial.Post')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('post', 'campaign')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='postQueue',
            field=models.ManyToManyField(blank=True, through='MMsocial.CampaignSequence', to='MMsocial.Post'),
        ),
    ]
