# Generated by Django 3.0.6 on 2020-09-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMUX', '0003_auto_20200921_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
