# Generated by Django 3.0.6 on 2020-09-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MMUX', '0005_auto_20200926_1422'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
