# Generated by Django 3.0.6 on 2020-09-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMUX', '0007_auto_20200926_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
